### ISSUE TITLE
atom-transcribe error

### ISSUE THREAD

**Issue by un1dade** [atom-extensions/atom-music#16]
hi everyone,

sorry for my ignorance but i'm new around here.
i'm getting this error whenever i try to toggle transcribe:
![Screenshot from 2019-03-13 10-16-26](https://user-images.githubusercontent.com/48514179/54271393-54f1c180-4579-11e9-8f4c-ed11b90d684d.png)

TypeError: Cannot set property 'ondblclick' of undefined
    at AtomTranscribeView.module.exports.AtomTranscribeView.initialize (/home/paulo/.atom/packages/atom-transcribe/lib/atom-transcribe-view.coffee:58:5)
    at AtomTranscribeView.View [as constructor] (/home/paulo/.atom/packages/atom-transcribe/node_modules/space-pen/lib/space-pen.js:184:25)
    at new AtomTranscribeView (/home/paulo/.atom/packages/atom-transcribe/lib/atom-transcribe-view.coffee:7:7)
    at Object.activate (/home/paulo/.atom/packages/atom-transcribe/lib/atom-transcribe.coffee:10:27)
    at Package.activateNow (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:11:2921510)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:11:1190169)
    at Emitter.emit (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:11:1191610)
    at CommandRegistry.handleCommandEvent (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:11:349687)
    at CommandRegistry.dispatch (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:11:348530)
    at AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:1:694295)
    at EventEmitter.t (/snap/atom/223/usr/share/atom/resources/app/static/<embedded>:1:701679)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)

cheers,
paulo

**Comment by UziTech** [comment]
looks like this is an issue for https://github.com/mbroedl/atom-transcribe

**Comment by vivi90** [comment]
I agree with @UziTech
