### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by willis325** [atom-extensions/atom-music#5]
Cannot find module 'atom-space-pen-views'
Hide Stack Trace
Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/atom-music/lib/atom-music-view.coffee:1:13)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/atom-music/lib/atom-music-view.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:UsersAdministratorAppDataLocalatomapp-1.8.0resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/atom-music/lib/atom-music.coffee:1:17)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/atom-music/lib/atom-music.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:UsersAdministratorAppDataLocalatomapp-1.8.0resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)

**Comment by sdinesh86** [comment]
Can you please share more details, which version of atom you are using.

**Comment by sdinesh86** [comment]
Closing this as, i dont have details on this
